theme:
  name: dark

title: Dhira Homelab
subtitle: Raspberry Pi 5 · Ubuntu 24.04 · Docker

pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: bookmarks
            groups:
              - title: Services
                links:
                  - title: Portainer
                    url: http://pi.local:9000
                    icon: docker
                  - title: CasaOS
                    url: http://pi.local:8080
                    icon: home
